openapi: 3.0.0
info:
  title: PawConnect API - PetCare
  version: 1.0.0
  description: API for managing pet care services like veterinarians, pet salons, and therapies.

paths:
  /petcare:
    post:
      summary: Register a pet care service
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PetCare'
            example:
              type: "Veterinarian"
              frequency: "Monthly"
      responses:
        '201':
          description: Pet care service successfully registered
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PetCare'
        '400':
          description: Invalid request payload
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    PetCare:
      type: object
      properties:
        type:
          type: string
          example: "Veterinarian"
        frequency:
          type: string
          example: "Monthly"
    
    Error:
      type: object
      properties:
        code:
          type: integer
          example: 400
        message:
          type: string
          example: "Invalid request payload"